version: '3.8'

services:
  db:
    image: mysql:8.0
    ports:
      - "3306:3306"  # Expõe a porta para o host
    environment:
      MYSQL_ROOT_PASSWORD: 140610
      MYSQL_DATABASE: popcitydash-chatbot
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 5

volumes:
  mysql_data: